// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unico.Core.API.Data;

namespace Unico.Core.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Unico.Core.API.Data.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("AREAP")
                        .HasColumnType("bigint");

                    b.Property<string>("BAIRRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CODDIST")
                        .HasColumnType("int");

                    b.Property<int>("CODSUBPREF")
                        .HasColumnType("int");

                    b.Property<string>("DISTRITO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGRADOURO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOME_FEIRA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUMERO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REFERENCIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGIAO5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGIAO8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGISTRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SETCENS")
                        .HasColumnType("bigint");

                    b.Property<string>("SUBPREFE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });
#pragma warning restore 612, 618
        }
    }
}
